### ISSUE TITLE
Integrate OM Web Video SDK into the test player

### ISSUE THREAD

**Issue by tmdbckr** [InteractiveAdvertisingBureau/VAST-Tester#19]
IAB has released the [OM Web Video SDK](https://iabtechlab.com/standards/open-measurement-sdk/) so players can easily interface with OMID-compliant measurement scripts.

Rather than using its own custom functionality, the test player could incorporate OM Web Video SDK to showcase its functionality and be in line with the industry standard.

Resources:
 - [OM Web Video SDK repo](https://github.com/InteractiveAdvertisingBureau/Open-Measurement-JSClients)
 - [OM Web Video SDK repo - Reference app](https://github.com/InteractiveAdvertisingBureau/Open-Measurement-JSClients/tree/master/reference-app-web)

**Comment by timdp** [comment]
Added in a01171435d500949d4fde57292b1a66e8395d8a7.
